-- FTC Whisper — Supabase setup script.
-- Safe to run multiple times (idempotent).
-- Run in Supabase SQL Editor: https://supabase.com/dashboard/project/_/sql

create extension if not exists "pgcrypto";

-- ── profiles table ─────────────────────────────────────────────────────────────
create table if not exists public.profiles (
    id         uuid primary key references auth.users(id) on delete cascade,
    email      text unique,
    full_name  text,
    role       text not null default 'user',
    created_at timestamptz not null default now()
);

-- Add any missing columns to an existing table (won't fail if already present).
-- Using a default on add so existing rows are never null.
alter table public.profiles
    add column if not exists email      text,
    add column if not exists full_name  text,
    add column if not exists created_at timestamptz default now();

-- Add role with default so existing rows get 'user' immediately (no nulls).
do $$
begin
    if not exists (
        select 1 from information_schema.columns
        where table_schema = 'public'
          and table_name   = 'profiles'
          and column_name  = 'role'
    ) then
        alter table public.profiles add column role text not null default 'user';
    end if;
end $$;

-- Ensure constraints and defaults are set (safe even if already set).
alter table public.profiles alter column role set default 'user';
alter table public.profiles alter column created_at set default now();

-- Backfill any existing users who don't have a profile row yet.
insert into public.profiles (id, email)
select u.id, u.email
from auth.users u
left join public.profiles p on p.id = u.id
where p.id is null;

-- ── Auto-create profile on new user signup ─────────────────────────────────────
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
    insert into public.profiles (id, email)
    values (new.id, new.email)
    on conflict (id) do update set email = excluded.email;
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users for each row execute function public.handle_new_user();

-- ── Admin helper ───────────────────────────────────────────────────────────────
create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public
as $$
    select exists (
        select 1 from public.profiles
        where id = auth.uid() and role = 'admin'
    );
$$;

grant execute on function public.is_admin() to authenticated;

-- ── Row-level security: profiles ──────────────────────────────────────────────
alter table public.profiles enable row level security;

drop policy if exists profiles_select_policy on public.profiles;
create policy profiles_select_policy on public.profiles
for select to authenticated
using (id = auth.uid() or public.is_admin());

drop policy if exists profiles_update_policy on public.profiles;
create policy profiles_update_policy on public.profiles
for update to authenticated
using  (id = auth.uid() or public.is_admin())
with check (id = auth.uid() or public.is_admin());

-- ── transcriptions table ───────────────────────────────────────────────────────
create table if not exists public.transcriptions (
    id               bigint generated by default as identity primary key,
    transcribed_text text,
    refined_text     text,
    refinement_mode  text,
    created_at       timestamptz not null default now(),
    user_id          uuid references auth.users(id) on delete cascade
);

alter table public.transcriptions
    add column if not exists user_id uuid references auth.users(id) on delete cascade;

alter table public.transcriptions
    alter column user_id    set default auth.uid(),
    alter column created_at set default now();

-- ── Row-level security: transcriptions ────────────────────────────────────────
alter table public.transcriptions enable row level security;

drop policy if exists transcriptions_select_policy on public.transcriptions;
create policy transcriptions_select_policy on public.transcriptions
for select to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists transcriptions_insert_policy on public.transcriptions;
create policy transcriptions_insert_policy on public.transcriptions
for insert to authenticated
with check (user_id = auth.uid() or public.is_admin());

drop policy if exists transcriptions_update_policy on public.transcriptions;
create policy transcriptions_update_policy on public.transcriptions
for update to authenticated
using  (user_id = auth.uid() or public.is_admin())
with check (user_id = auth.uid() or public.is_admin());

drop policy if exists transcriptions_delete_policy on public.transcriptions;
create policy transcriptions_delete_policy on public.transcriptions
for delete to authenticated
using (user_id = auth.uid() or public.is_admin());

-- ── Realtime ───────────────────────────────────────────────────────────────────
do $$ begin
    begin
        alter publication supabase_realtime add table public.profiles;
    exception when duplicate_object then null;
    end;
    begin
        alter publication supabase_realtime add table public.transcriptions;
    exception when duplicate_object then null;
    end;
end $$;

-- ── Grant admin role to master account ────────────────────────────────────────
update public.profiles set role = 'admin' where email = 'ryan.murphy@ftc-ss.com';
